apiVersion: skaffold/v4beta4
kind: Config
build:
  artifacts:
    # - image: mrlucciola/client
    #   context: ./
    #   sync:
    #     manual:
    #       - src: ./client/src/**/*.ts
    #         dest: .
    #   docker:
    #     dockerfile: ./client/Dockerfile
    - image: mrlucciola/comments
      context: ./
      sync:
        manual:
          - src: ./services/comments/src/**/*.ts
            dest: .
      docker:
        dockerfile: ./services/comments/Dockerfile
    - image: mrlucciola/event-bus
      context: ./
      sync:
        manual:
          - src: ./services/event-bus/src/**/*.ts
            dest: .
      docker:
        dockerfile: ./services/event-bus/Dockerfile
    - image: mrlucciola/moderation
      context: ./
      sync:
        manual:
          - src: ./services/moderation/src/**/*.ts
            dest: .
      docker:
        dockerfile: ./services/moderation/Dockerfile
    - image: mrlucciola/posts
      context: ./
      sync:
        manual:
          - src: ./services/posts/src/**/*.ts
            dest: .
      docker:
        dockerfile: ./services/posts/Dockerfile
    - image: mrlucciola/query
      context: ./
      sync:
        manual:
          - src: ./services/query/src/**/*.ts
            dest: .
      docker:
        dockerfile: ./services/query/Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./k8s/*
    - ./client/k8s/*
    - ./services/*/k8s/*
deploy:
  kubectl: {}